### ISSUE TITLE
Pufflescape not saving

### ISSUE THREAD

**Issue by DiamondFireYT** [solero/houdini#30]
Pufflescape isn't saving. It doesn't have a handler nor is it on the progress tracker?

**Comment by ketnipz** [comment]
I am assuming you mean Pufflescape, the mini-game. There isn't a game called Puffle Escape.

This game doesn't send packets to update any kind of progression system or ask for progression status when it starts up. So I assumed progress doesn't get saved. I could be wrong about this, perhaps there is something I am missing.

Am happy to implement any handlers required for this feature, but I don't know the packet type/structure because the game doesn't ask for anything!

**Comment by zombiestruck** [comment]
I have looked into the game and it seems it was never implemented into the game. In the SWF it has
`public function getSaveGame() : String
      {
         return null;
      }`

**Comment by zombiestruck** [comment]
Upon further research, it should save unlocked levels, but not the information regarding the levels.

**Comment by zombiestruck** [comment]
It seems to save the data through DLSManager rather than a packet, however I could be wrong about that.

**Comment by nhaar** [comment]
Pufflescape does not save the berries (which is good for its functionality), but it does save your progress in some way, I think it might be based on stamps
