### ISSUE TITLE
Suggestion - Create issue templates?

### ISSUE THREAD

**Issue by Zaseth** [solero/houdini#46]
Since there's a lot of things that could go wrong when setting up a CPPS using Houdini, I think it's a good practice to create an issue template for this repository. Something like specifying what version(s) you're running could be a start of this template.

**Comment by ketnipz** [comment]
I think this is a great idea!

We don't really have a versioning system for Houdini set out yet, I guess because there's so many changes still happening that it doesn't make sense.

Perhaps we can use this thread to get some ideas of what a good template would be?

I'll give it a go first:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Install Method**
Wand/Manual setup/Other (please specify)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If this is a bug that happens in-game, post a screenshot with dev-tools open in your browser (F12 to open).

**Server Info:**
 - OS: [e.g. Windows/Linux/macOS]

**Additional context**
Add any other context about the problem here.

**Comment by rsakeys** [comment]
Might be helpful to also add:

**Client Type:**
(vanilla or/and legacy)

**Comment by Zaseth** [comment]
This all sounds good and well, maybe it's also applicable for pull requests?

**Comment by ketnipz** [comment]
I created the new template and issued a pull request. Let me know what you think.

> This all sounds good and well, maybe creating such template is also applicable for pull requests?

I'm not sure about this since pull requests can vary in purpose quite a bit. Do other projects do this? Is there something you had in mind for a template?

**Comment by Zaseth** [comment]
I believe Github provides support for creating pull request templates, I could be wrong. This should be somewhere in the repository settings, it's like a startup guide for setting up your repository.

**Comment by ketnipz** [comment]
GitHub seems to only suggest templates for bug reports and feature requests.

**Comment by Zaseth** [comment]
I see, then you can ignore my mistake. Thanks for creating an issue template!
